runtime: python39

env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: "False"
  CHUNK_SIZE: "300"
  CHUNK_OVERLAP: "50"
  MAX_CHUNKS: "4"
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?tests/.*$
- node_modules/
- venv/
- __pycache__/
- credentials.json
- token.json
- document.index
- documents.json
